### PR TITLE
#993 Support broker properties from JSON files

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Review by gaohoward — APPROVED** [review]
LGTM. btw the image quay.io/artemiscloud/activemq-artemis-broker-kubernetes@sha256:9093e08d49634cb4dae18942dfa2a488f0607eed76fb75890d93914833db9a93 seems gone (deleted?) when I run the tests again.

**Review by gtully — APPROVED** [review]
looks sensible and will be a big win for addresses and security config

**Comment by brusdev** [comment]
> LGTM. btw the image quay.io/artemiscloud/activemq-artemis-broker-kubernetes@sha256:9093e08d49634cb4dae18942dfa2a488f0607eed76fb75890d93914833db9a93 seems gone (deleted?) when I run the tests again.

I updated the related images to 2.37.0 and removed the references to the temporary activemq-artemis-broker-kubernetes container images.

**Comment by brusdev** [comment]
All tests passed.

**Pull request merged**
