### PR TITLE
[#612] Update doc examples

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Review by SantoshKumarArjunan — COMMENTED** [review]
Hi @brusdev -- 
line #83 in [docs/tutorials/using_operator.md](https://github.com/artemiscloud/activemq-artemis-operator/pull/613/files#diff-259d4296e8e501de47756ba9bf2ccfc68bdf0355be36fb055661d93bdad5929a)

-- Maybe you also want to change the old file name "examples/artemis-basic-deployment.yaml" into the new file name?

**Comment by SantoshKumarA** [comment]
@brusdev , On a quick glance, I could not find anything else as obvious to be corrected. So all looks good. On the other hand, I tried to deploy by following the document, but somehow the broker deployment is not successful. When I see the operator pod logs, I see the following. Could this be a reason for me to unable to continue further?

`$ minikube kubectl -- logs activemq-artemis-controller-manager-68867db6f9-2v6g8 -n myproject
Executing entrypoint
exec /home/activemq-artemis-operator/bin/activemq-artemis-operator
2023-06-13T13:43:42.839Z        INFO    setup   Go Version: go1.17.13
2023-06-13T13:43:42.839Z        INFO    setup   Go OS/Arch: linux/amd64
2023-06-13T13:43:42.839Z        INFO    setup   Version of operator-sdk: 1.15.0
2023-06-13T13:43:42.839Z        INFO    setup   Version of the operator: 1.0.11 2023-03-22T18:19:18
2023-06-13T13:43:42.839Z        INFO    setup   Supported ActiveMQArtemis Kubernetes Image Versions: 2.21.0 2.22.0 2.23.0 2.25.0 2.26.0 2.27.0 2.28.0
2023-06-13T13:43:42.839Z        INFO    setup   Got operator namespace  {"operator ns": "myproject"}
2023-06-13T13:43:42.839Z        INFO    setup   setting up operator to watch local namespace
2023-06-13T13:43:43.092Z        INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "0.0.0.0:8383"}
2023-06-13T13:43:43.597Z        INFO    setup   service account name: activemq-artemis-controller-manager
2023-06-13T13:43:43.597Z        INFO    setup   NOT Setting up webhook functions        {"ENABLE_WEBHOOKS": "false"}
2023-06-13T13:43:43.597Z        INFO    setup   starting the Cmd.
2023-06-13T13:43:43.597Z        INFO    controller_v1beta1activemqartemisaddress        Setting up address observer
2023-06-13T13:43:43.597Z        INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8383"}
I0613 13:43:43.597668       1 leaderelection.go:248] attempting to acquire leader lease myproject/d864aab0.amq.io...
2023-06-13T13:43:43.597Z        INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
2023-06-13T13:43:43.597Z        INFO    addressobserver_activemqartemisaddress  #### Started workers
E0613 13:43:43.602962       1 leaderelection.go:334] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
E0613 13:43:46.184753       1 leaderelection.go:330] error retrieving resource lock myproject/d864aab0.amq.io: leases.coordination.k8s.io "d864aab0.amq.io" is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
E0613 13:43:49.082476       1 leaderelection.go:330] error retrieving resource lock myproject/d864aab0.amq.io: leases.coordination.k8s.io "d864aab0.amq.io" is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
E0613 13:43:51.900421       1 leaderelection.go:330] error retrieving resource lock myproject/d864aab0.amq.io: leases.coordination.k8s.io "d864aab0.amq.io" is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
E0613 13:43:55.691152       1 leaderelection.go:330] error retrieving resource lock myproject/d864aab0.amq.io: leases.coordination.k8s.io "d864aab0.amq.io" is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
E0613 13:43:58.684756       1 leaderelection.go:330] error retrieving resource lock myproject/d864aab0.amq.io: leases.coordination.k8s.io "d864aab0.amq.io" is forbidden: User "system:serviceaccount:myproject:activemq-artemis-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "myproject"
`

I am sure this needs to be reported as a separate bug as unable to continue from step-3 at https://artemiscloud.io/docs/tutorials/using_operator/#step-3---deploying-activemq-artemis-broker-in-the-cloud though I use the following file 'examples/artemis/artemis_single.yaml' now.

**Comment by brusdev** [comment]
@SantoshKumarA I have just updated my PR with new instructions to install the operator:
```
      $ cd activemq-artemis-operator
      $ ./deploy/install_opr.sh
```

The new instructions to update the operator should fix your issue.

**Comment by SantoshKumarA** [comment]
@brusdev , Thank you so muhc @brusdev .. I would like to share how it worked for me.  The install_opr.sh is very much helpful too.

I tried multiple times, install and undeploy. finally, the following order worked out. Hope this may help for updating the documentation or someone who will face issues like me. thank you again. BTW, I still believe that some of the below steps are not needed. But I do not want to cleanup again and try from the beginning. 😊

cd activemq-artemis-operator
$ ./deploy/undeploy_all.sh


cd activemq-artemis-operator
kubectl create -f deploy/service_account.yaml --namespace myproject
kubectl create -f deploy/role.yaml --namespace myproject
kubectl create -f deploy/role_binding.yaml --namespace myproject


kubectl create namespace activemq-artemis-operator
kubectl config set-context --current --namespace activemq-artemis-operator
./deploy/install_opr.sh

kubectl get pod -n activemq-artemis-operator
kubectl create -f examples/artemis/artemis_single.yaml -n activemq-artemis-operator

----------

$ kubectl create namespace activemq-artemis-operator
namespace/activemq-artemis-operator created

$ kubectl config set-context --current --namespace activemq-artemis-operator
Context "minikube" modified.


$ ./deploy/install_opr.sh
Deploying operator to watch single namespace
./deploy/install_opr.sh: line 7: oc: command not found
customresourcedefinition.apiextensions.k8s.io/activemqartemises.broker.amq.io created
customresourcedefinition.apiextensions.k8s.io/activemqartemisaddresses.broker.amq.io created
customresourcedefinition.apiextensions.k8s.io/activemqartemisscaledowns.broker.amq.io created
customresourcedefinition.apiextensions.k8s.io/activemqartemissecurities.broker.amq.io created
serviceaccount/activemq-artemis-controller-manager created
role.rbac.authorization.k8s.io/activemq-artemis-operator-role created
rolebinding.rbac.authorization.k8s.io/activemq-artemis-operator-rolebinding created
role.rbac.authorization.k8s.io/activemq-artemis-leader-election-role created
rolebinding.rbac.authorization.k8s.io/activemq-artemis-leader-election-rolebinding created
configmap/activemq-artemis-manager-config created
deployment.apps/activemq-artemis-controller-manager created

$ kubectl create -f examples/artemis/artemis_single.yaml -n activemq-artemis-operator


$ kubectl get pod -n activemq-artemis-operator
NAME                                                   READY   STATUS    RESTARTS      AGE
activemq-artemis-controller-manager-68867db6f9-dx8xj   1/1     Running   3 (95s ago)   133m
artemis-broker-ss-0                                    1/1     Running   0             131m

**Comment by brusdev** [comment]
@SantoshKumarA thanks for your feedback, starting with a clean environment the following steps, should be enough:
```
kubectl create namespace activemq-artemis-operator
kubectl config set-context --current --namespace activemq-artemis-operator
./deploy/install_opr.sh
```

**Pull request merged**
