### PR TITLE
fix process resources tracking secret for crd state

### PR DESCRIPTION
**Pull request by gtully**

### CODE REVIEW

**Comment by gtully** [comment]
the check was after the delete, so was racing with its self!

**Comment by RoddieKieley** [comment]
@gtully It appears this work was superceeded by that included in #171 ? Is there anything here that should be required?

**Comment by gaohoward** [comment]
@gtully maybe we can safely close this.

**Comment by RoddieKieley** [comment]
Looks like commit [599fc156b2ba578b264510856d9a5796484ee675](https://github.com/artemiscloud/activemq-artemis-operator/pull/170/commits/599fc156b2ba578b264510856d9a5796484ee675 above was cherry-picked and made it's way into main as commit [a594e86c7c0b584332b85100d6d4a616fc9dc745](https://github.com/artemiscloud/activemq-artemis-operator/commit/a594e86c7c0b584332b85100d6d4a616fc9dc745)

**Pull request closed without merging**
