### PR TITLE
[#968] Replace HTTP test proxy with SSH tunnels

### PR DESCRIPTION
**Pull request by brusdev**
SSH tunnels support HTTPS and other tcp connections.

### CODE REVIEW

**Comment by gaohoward** [comment]
@brusdev  I just found that when 'test' namespace already exists, this line panicks:

https://github.com/artemiscloud/activemq-artemis-operator/blob/0babfdc623fc29ce8b721331756ff21b6baf1543/controllers/suite_test.go#L223

I think we should use 
`Expect(err == nil || errors.IsAlreadyExists(err)).To(BeTrue())`

**Comment by brusdev** [comment]
> @brusdev I just found that when 'test' namespace already exists, this line fails:
> 
> https://github.com/artemiscloud/activemq-artemis-operator/blob/0babfdc623fc29ce8b721331756ff21b6baf1543/controllers/suite_test.go#L223
> 
> I think we should use `Expect(err == nil || errors.IsAlreadyExists(err)).To(BeTrue())`

@gaohoward I have just fixed it

**Review by gtully — APPROVED** [review]
great to have the https path sorted, looks great.

**Review by gaohoward — APPROVED** [review]
I give my approval as it works. I'm still having issues but I think that's specific to my special environment. I'll investigate afterwards.

**Review by gaohoward — APPROVED** [review]

**Pull request merged**
