### PR TITLE
[#877 #880] deprecate address,security and addressSettings in favour …

### PR DESCRIPTION
**Pull request by gtully**
…of brokerProperties

### CODE REVIEW

**Review by brusdev — COMMENTED** [review]
@gtully what about enforcing the deprecation with the [version deprecation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-deprecation)?

**Comment by gtully** [comment]
That assumes a change in the version. We have kept v1beta1 for some time. I think it would only make sense if we were changing the version

**Comment by gtully** [comment]
but it does give better feedback. I will investigate a little. thanks for the idea :-)

**Comment by gtully** [comment]
added the annotation, i did not yet get the api server to return the warning, that is with mk and the updated crds

**Comment by gtully** [comment]
success!
```
[activemq-artemis-operator]$ kubectl apply -f examples/address/address_queue.yaml 
Warning: The ActiveMQArtemisAddress CRD is deprecated. Use the spec.brokerProperties attribute in the ActiveMQArtemis CR to create addresses and queues instead
activemqartemisaddress.broker.amq.io/artemis-address-queue created
```

**Pull request merged**
