### PR TITLE
[NO-ISSUE] remove metadata.application from CRs

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Comment by brusdev** [comment]
@pwright I see other CRs with the `metadata.application` field, see https://github.com/search?q=repo%3Aartemiscloud%2Factivemq-artemis-operator%20%22application%3A%22&type=code

Are you planning to clean the other CRs too?

**Review by gaohoward — APPROVED** [review]

**Comment by pwright** [comment]
@brusdev I updated config/crs/broker_activemqartemis_cr.yaml but I don't know whether I should touch older samples, eg config/samples/broker_activemqartemis_v2alpha1_cr.yaml (was that metadata relevant for V2alpha1?)

**Comment by brusdev** [comment]
@pwright in all the versions of ActiveMQArtemis CRD the type of the metadata field is [ObjectMeta v1 meta](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#objectmeta-v1-meta) that doesn't contain a field with the name `application`. I think that `metadata.application` can be safely removed from all CRs.

**Comment by pwright** [comment]
@brusdev  done, but doesn't this affect metrics docs at https://github.com/artemiscloud/activemq-artemis-operator/pull/691/files#diff-74b1fb1892c01511e4db552301d6a19757f3a8ab93b793dc94c91e66ff452628L932

or should the match criteria change?

**Comment by brusdev** [comment]
> @brusdev done, but doesn't this affect metrics docs at https://github.com/artemiscloud/activemq-artemis-operator/pull/691/files#diff-74b1fb1892c01511e4db552301d6a19757f3a8ab93b793dc94c91e66ff452628L932
> 
> or should the match criteria change?

@pwright that is fine because the operator adds a label with the key `application`, see https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.15/pkg/utils/selectors/label.go#L4

The changes LGTM could you squash your commits?

**Comment by brusdev** [comment]
@pwright thanks for your contribution

**Pull request merged**
