### PR TITLE
[#348] Revert redelivery factor fields to *float32

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Review by gaohoward — APPROVED** [review]

**Comment by gaohoward** [comment]
the checkFloat32AsString should be changed to checkFloat32

**Comment by gtully** [comment]
I don't see any down side to reverting these changes to the previous cr versions we retain, and I think it is a necessary part of being able to write a test to verify the need for conversion of some sort.

**Comment by gtully** [comment]
I will try and make a test on this branch

**Comment by gtully** [comment]
There may be some value in using json.Number, not sure yet what that entails. will investigate, would work for a string value that is a float format as well as a plain string.
If we can get into this branch:
https://github.com/kubernetes-sigs/json/blob/main/internal/golang/encoding/json/decode.go#L1088

**Comment by brusdev** [comment]
@gtully your suggestion to use json.Number to fix the conversion issue worked

**Pull request closed without merging**
