### PR TITLE
[#1007] respect deployed resource on PVC reconcile and fill in volume…

### PR DESCRIPTION
**Pull request by gtully**
…Mode default

### CODE REVIEW

**Comment by gtully** [comment]
Worth some thought is the ObjectMeta in the PVC template, not sure it is  good idea.

**Review by brusdev — APPROVED** [review]
Using one function for both the default PV and the ExtraVolumeClaimTemplates is a great idea!

**Comment by brusdev** [comment]
Full test-suite passed

**Comment by gtully** [comment]
> Worth some thought is the ObjectMeta in the PVC template, not sure it is good idea.

I am going to leave it, we don't add the same default labels as we do for the persistenceEnabled PVC, so there possibly will be the need to add labels. A resourceTemplate will work in this case also. Maybe it is a good convenience.

**Pull request merged**
