### PR TITLE
Introduce shortnames into CR/Ds

### PR DESCRIPTION
**Pull request by michalxo**
I have tried to implement short names as described in #392 
Currently I did `aa` and `ac`. Easy to pick one or completely different after some broader discussion.

### CODE REVIEW

**Review by brusdev — COMMENTED** [review]
@michalxo nice improvement, I would only use `ac` shortnames

**Comment by brusdev** [comment]
I'll close this PR because the current version of Kubernetes doesn't provide good support for shorthame conflicts causing the impossibility of using conflicted CRDs.

**Comment by brusdev** [comment]
I would propose to keep only shortnames starting with `ac`

**Comment by michalxo** [comment]
As in voting `ac` prefix won, I have updated this PR and should be ready to merge.

**Comment by brusdev** [comment]
could you update the bundle/manifests too?

**Comment by gtully** [comment]
I like the idea of short names, and am in favour of aa for activemqartemis, but i think the other CRD's don't need this love. I have added deprecation to artemissecurty in the past week due to it needing restarts and think the limitations of addresses (single queue, using jmx etc) will force it to be deprecated also in favour of brokerProperties or config map references.
in short, just aa for ActivemqArtemisCRs makes sense to me.

**Review by brusdev — APPROVED** [review]

**Pull request merged**
