### PR TITLE
support StorageClassName on PVC

### PR DESCRIPTION
**Pull request by rohanmars**
support setting StorageClassName on PVC

### CODE REVIEW

**Comment by gaohoward** [comment]
Hi If you need to add new options you have to change the CRD definitions and bump the crd version (i.e. from current broker v2alpha4 to v2alpha5).

**Comment by rohanmars** [comment]
will do. I'll update the code/PR.

**Comment by rohanmars** [comment]
@gaohoward when you say bump the crd do you mean add a new version v2alpha5 and generate new clients etc?  How do you do the code generation part? The project doesn't have instructions that are reproducible it seems and i'm a bit clueless how you would call the code-generator.

**Comment by gaohoward** [comment]
@rohanmars yes the code gen part seems broken. You have manually do it.
Take a look at current version stuff and just copy them over and do search replace.
But I think the best approach is to fix this issue. I'm going to raise another issue about that.

**Comment by gaohoward** [comment]
https://github.com/artemiscloud/activemq-artemis-operator/issues/51

**Comment by johgoe** [comment]
Currently there is a unreleased v2alpha5 Version on master. Is is it possible to merge this PR into it? Seems for me like only one line have to be changed for it and this feature would be very helpful for us.

**Comment by gaohoward** [comment]
btw we switched dev branch from master to main.

**Comment by gaohoward** [comment]
Hi @rohanmars I've ported your PR into a new PR https://github.com/artemiscloud/activemq-artemis-operator/pull/169 which bases on the new operator-sdk with a test. I mentioned that the work is from your PR in the commit messages. Please have a look when you got time and raise concerns if any. Thanks!

**Comment by RoddieKieley** [comment]
Closing as per issue #168 which via PR [#169](https://github.com/artemiscloud/activemq-artemis-operator/pull/169) brought these changes forward and added a test to the more recent unit tests.

**Pull request closed without merging**
