### PR TITLE
Improvements for podSecurityContext

### PR DESCRIPTION
**Pull request by johgoe**
Added   additional securityContext support for https://github.com/artemiscloud/activemq-artemis-operator/issues/48
```
securityContext:     
      runAsGroup: 3000
      fsGroup: 2000
```

### CODE REVIEW

**Comment by johgoe** [comment]
@gaohoward May you be able to check if the way I added a new schema version is right. I did it manually as #51 is not fixed yet.

**Comment by gaohoward** [comment]
@johgoe Hi, recently the project has upgraded to use new operator-sdk v1.15.0 and the whole project layout has changed a lot.
Can you please update your PR ? currently the CRD version is on v1beta1. Please take a look at the readme and docs/quickstart.md. Any questions pls let me know. Thanks!

**Comment by gaohoward** [comment]
also the dev branch is moved to 'main'

**Comment by gaohoward** [comment]
@johgoe That's fine. Thanks!

**Comment by johgoe** [comment]
@gaohoward As storageClassNames is already done in #168, I added my changes for securityContext only.

**Comment by johgoe** [comment]
@gaohoward May you able to check, if the PR is ok now?

**Comment by johgoe** [comment]
Seems to be already implemented

podSecurityContext:  supports several parameters

```
    podSecurityContext:  :
      fsGroup: 185
      runAsUser: 185
```

Seems like podSecurityContext is new securityContext, we should use.

**Pull request closed without merging**
