### PR TITLE
Draft: [481] Custom Labels for Services and Pods

### PR DESCRIPTION
**Pull request by davidlanouette**
Apply custom labels to most resources that are created by the operator.

Not all resources have labels, so some - like Containers, EnvVar's, etc.

### CODE REVIEW

**Comment by davidlanouette** [comment]
This needs additional tests to make sure all resources have the labels applied correctly.  But, it's in generally good shape to review.

**Comment by brusdev** [comment]
@davidlanouette thanks for your PR but there is also the issue #588 related to custom labels. The solution discussed in the issue #588 is that the ActiveMQArtemis CR should have the field labels in acceptor, connector and console too.

**Comment by davidlanouette** [comment]
@brusdev Thanks for the note.  Looking at that issue, it looks like it's _mostly_ a duplicate of 481.  I'll comment on that issue.

Regardless, I'll add see about incorporating the comments in that issue here.

**Comment by brusdev** [comment]
@davidlanouette I think that we can close this this PR because the solution implemented by #737 already allows [Custom Labels and Annotations on supporting resources; Services, Ingress, Secrets etc.](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#custom-labels-and-annotations-on-supporting-resources-services-ingress-secrets-etc). Feel free to reopen it if I'm missing something.

**Pull request closed without merging**
