### PR TITLE
[#505] Fix ActiveMQ Artemis upgrades

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Comment by gtully** [comment]
I had previously deprecated the upgrades attribute thinking that a version string would be sufficient. It may be that there is a need for a postfix to lock it down, x.y.z-final or some thing like that. Maybe the boolean is still necessary if a postfix is ugly or not sufficient.
see: https://github.com/artemiscloud/activemq-artemis-operator/commit/1cb7aacca805f5efdbc8b75b803c132fb6c6cc90#diff-1160c62501def02fcbb55235053bd8eb8a3c6b8e715b3350b4c844d6c3f1a85eR352

**Comment by gtully** [comment]
recalling some more thinking, x.y.z can only go so far, cve or patches that come via new bundles and via operator updates will leave version information out of date. Tags can move. The only way to avoid image update/rollout in those cases is to specify the image tag in the CR. Maybe we need to make it easier to identify the image that is in play such that the CR can be updated with the correct information with by the user.
That could be a use case for putting it in the status, but it would be the current image, not the desired image that is in the status.

**Comment by gtully** [comment]
actually, maybe the status contains:
observed image: ...
upgradeable = no (if image is specified) |major|minor (depending on the presence and specificity of the  version string).
I wonder if it would make a good Condition?

**Comment by brusdev** [comment]
Regardless of this PR I think that the CR status should include the current ActiveMQ Artemis version. The images are a bit raw for a user.

**Comment by brusdev** [comment]
Closed, see the issue #505 for further details.

**Pull request closed without merging**
