### PR TITLE
[#837] Documentation and test for setting PriorityClassName

### PR DESCRIPTION
**Pull request by kevinfrommelt**
^

### CODE REVIEW

**Comment by kevinfrommelt** [comment]
Looks like the tests don't currently run b/c of this issue https://github.com/kubernetes-sigs/controller-runtime/issues/2720

**Review by brusdev — COMMENTED** [review]
@kevinfrommelt thanks for your PR but you could already customize the priorityClassName and other podSpec fields by using a strategic merge patch, for further details see https://github.com/artemiscloud/activemq-artemis-operator/issues/837#issuecomment-2016538868

After #758 new fields to customize the resource managed by the operator are added only for use cases in which a [strategic merge patch](https://github.com/artemiscloud/activemq-artemis-operator/blob/1.1.0/docs/help/operator.md#custom-mods-via-a-strategic-merge-patch) doesn't work or would be too much complex.

You could change your PR to add a doc and a test to set the `priorityClassName` by using a [strategic merge patch](https://github.com/artemiscloud/activemq-artemis-operator/blob/1.1.0/docs/help/operator.md#custom-mods-via-a-strategic-merge-patch) if that works for your use case.

**Comment by kevinfrommelt** [comment]
@brusdev Thanks for the info. I'll update the PR to just include docs and tests like you suggested.

**Comment by kevinfrommelt** [comment]
@brusdev This is ready for review

**Review by brusdev — APPROVED** [review]
@kevinfrommelt great work!!!

**Comment by brusdev** [comment]
@kevinfrommelt thanks for your contribution and for investigating the CI error, I fixed it in #839

**Pull request merged**
