### PR TITLE
[#495] regex login config secret validation that will trap syntax err…

### PR DESCRIPTION
**Pull request by gtully**
…ors and report in the cr.Status

### CODE REVIEW

**Comment by gtully** [comment]
I am thinking this validation, being general, it may not cover every case, it may make sense to have a operator level env var or argument that can suppress it. --disable-jaas-config-syntax-validation or some such thing?

**Comment by gtully** [comment]
second thought - store the regexp in an env var, that can be enhanced or can be set to "" to disable. in that way, it is still trivial to disable but it is also possible to improve.

**Comment by ruromero** [comment]
> I am thinking this validation, being general, it may not cover every case, it may make sense to have a operator level env var or argument that can suppress it. --disable-jaas-config-syntax-validation or some such thing?

Why not `strict-validation` and then don't make the jaas-validation cause the resource to not be ready? With this you can have the following conditions:
- jaas-validation: False 
- ready: True

**Comment by gtully** [comment]
not sure on the value of valid false, I think the real use case here is if there is something valid in the login.confg and the regex is giving a false negative, in that case the regex needs to be improved or disabled, but continually reporting the false negative is of little use.
I am going with an env var to override - JAAS_CONFIG_SYNTAX_MATCH_REGEX="" will disable or can indeed improve it

**Pull request merged**
