### PR TITLE
Update jolokia.go

### PR DESCRIPTION
**Pull request by Nanmozhi22**
Disabled TLS certificate check

### CODE REVIEW

**Comment by brusdev** [comment]
@Nanmozhi22 can you create an issue at https://github.com/artemiscloud/activemq-artemis-operator/issues/new/choose and add the number of the issue at the beginning of the commit message?

**Comment by Nanmozhi22** [comment]
@brusdev Thank you for your response!

But I have already opened an issue https://github.com/artemiscloud/activemq-artemis-operator/issues/919 and committed the code . 

Do you still want me to create a new issue and the number of the commit ? It would be great if you can clarify this.

Thanks
Nan

**Comment by brusdev** [comment]
@Nanmozhi22 #919 is fine, you just need to add the number of the issue at the beginning of the commit message, i.e.
```
[#919] Update jolokia.go
```

**Comment by brusdev** [comment]
I'm wondering if this change can break deployment with a console secured by self signed certificates

**Comment by brusdev** [comment]
@Nanmozhi22 I think this PR is a good security improvement but we need to figure out a solution for deployments with a console secured by self signed certificates

**Comment by Nanmozhi22** [comment]
@brusdev got it , Just curious until if we figure out a solution this PR can't be merged ?

**Comment by brusdev** [comment]
> @brusdev got it , Just curious until if we figure out a solution this PR can't be merged ?

@Nanmozhi22 I don't think so, I'll move it to draft

**Comment by brusdev** [comment]
Incorporated by #1038

**Pull request closed without merging**
